Repository gitcoinco/codefund, pull requests merged in 2018-10, with the labels that each got.

#348 Update dependencies with security vulnerabilities
  Gemfile
  Gemfile.lock
  assets/package-lock.json
  assets/package.json
Labels: security

#356 Add advertiser prospectus, fixed typo on home page
  assets/static/docs/codefund-prospectus-q4-2018.pdf
  lib/code_fund_web/endpoint.ex
  lib/code_fund_web/templates/page/advertisers.html.eex
  lib/code_fund_web/templates/page/index.html.eex
  lib/code_fund_web/templates/page/scripts.index.html.eex
Labels: in progress

#357 Add Open Collective to README
  README.md
Labels: in progress

#355 Work on campaign form to show/hide enable/disable fields based on role
  assets/src/controllers/campaign_form_controller.js
  lib/ad_service/math/impression.ex
  lib/code_fund_web/controllers/campaign_controller.ex
  lib/code_fund_web/templates/campaign/form.html.eex
  lib/code_fund_web/templates/campaign/show.html.eex
  lib/code_fund_web/templates/user/show.html.eex
  test/ad_service/math/impression_test.exs
  test/code_fund_web/controllers/campaign_controller_test.exs
Labels: bug, enhancement, in progress, security

#360 Add GA event tracking for non-authenticated pages
  assets/src/controllers/event_track_controller.js
  assets/src/home.js
  assets/webpack/webpack.common.js
  lib/code_fund_web/templates/layout/home.html.eex
  lib/code_fund_web/templates/page/advertisers.html.eex
  lib/code_fund_web/templates/page/publishers.html.eex
Labels: in progress

#359 bean/gh-331_country_protocol_bug
  lib/framework/geolocation/protocol.ex
  lib/framework/geolocation/record/protocol.ex
  test/framework/geolocation/protocol_test.exs
  test/framework/geolocation/record/protocol_test.exs
Labels: in progress

#367 bean/gh-304_campaign_tags
  lib/code_fund/factory.ex
  lib/code_fund/properties/properties.ex
  lib/code_fund/schemas/campaign.ex
  lib/code_fund/tasks/audience_tag_to_campaign_copy.ex
  lib/code_fund_web/controllers/campaign_controller.ex
  lib/code_fund_web/controllers/property_controller.ex
  lib/code_fund_web/templates/audience/form.html.eex
  lib/framework/ecto/changeset/date.ex
  lib/framework/ecto/date.ex
  lib/framework/generic_enums.ex
  priv/repo/migrations/20181004211222_add_tags_to_campaign.exs
  test/code_fund_web/controllers/campaign_controller_test.exs
  test/tasks/audience_tag_to_campaign_copy_test.exs
Labels: in progress

#364 Update publisher form
  lib/code_fund_web/templates/page/publishers.html.eex
Labels: In progress

#371 Improve UX around dropdowns
  assets/.prettierrc.js
  assets/src/css/_selectize.bootstrap4.scss
  assets/src/css/codefund-framework/_custom.scss
  assets/src/onload.js
  lib/code_fund/assets/assets.ex
  lib/code_fund/audiences/audiences.ex
  lib/code_fund/creatives/creatives.ex
  lib/code_fund/templates/templates.ex
  lib/code_fund/users/users.ex
  lib/code_fund_web/controllers/campaign_controller.ex
  lib/code_fund_web/controllers/property_controller.ex
  lib/code_fund_web/controllers/user_controller.ex
  lib/code_fund_web/templates/campaign/index.html.eex
  lib/code_fund_web/templates/property/index.html.eex
  lib/framework/phoenix/form/helpers.ex
  test/code_fund_web/controllers/track_controller_test.exs
  test/code_fund_web/controllers/user_controller_test.exs
  test/framework/geolocation_test.exs
Labels: Enhancement, In progress

#346 Add support to extract values from user_impressions
  .env-sample
  config/configs/exq.exs
  config/prod.exs
  lib/code_fund/application.ex
  lib/code_fund/schemas/user_impression.ex
  lib/code_fund/stats/user_impressions.ex
  lib/code_fund_web/router.ex
  mix.exs
  test/code_fund/stats/user_impressions_test.exs
Labels: Enhancement, In progress

#373 bean/gh-365_serve_ads_from_tags
  lib/ad_service/query/for_display.ex
  lib/ad_service/server.ex
  lib/code_fund/audiences/audiences.ex
  lib/code_fund/properties/properties.ex
  lib/code_fund_web/templates/audience/index.html.eex
  lib/code_fund_web/templates/property/index.html.eex
  test/ad_service/query/for_display_test.exs
  test/ad_service/server_test.exs
  test/code_fund_web/controllers/api/ad_serve_controller_test.exs
  test/code_fund_web/controllers/api/v1/property/impression_controller_test.exs
  test/code_fund_web/controllers/property_controller_test.exs
Labels: In progress

#377 Support debugging of GA events in prod
  assets/src/controllers/event_track_controller.js
Labels: In progress

#386 WIP fix_user_impression_stats_test
  test/code_fund/stats/user_impressions_test.exs
Labels: In progress

#388 bean/fix_tag_impression_query
  lib/ad_service/query/for_display.ex
  test/ad_service/query/for_display_test.exs
Labels: In progress

#379 Bean/gh 376 fallback campaign boolean
  lib/ad_service/impression/manager.ex
  lib/ad_service/query/for_display.ex
  lib/code_fund/schemas/campaign.ex
  lib/code_fund/schemas/property.ex
  lib/code_fund_web/controllers/campaign_controller.ex
  priv/repo/migrations/20181010203633_add_fallback_campaign_boolean_to_campaigns.exs
  test/ad_service/impression/manager_test.exs
  test/ad_service/query/for_display_test.exs
  test/ad_service/server_test.exs
  test/code_fund/stats/user_impressions_test.exs
  test/code_fund_web/controllers/campaign_controller_test.exs
Labels: In progress

#389 fix_query_clause_duplication
  lib/ad_service/query/for_display.ex
Labels: In progress

#395 Use gtag interface for GA events
  assets/src/controllers/event_track_controller.js
Labels: Bug, In progress

#396 do_not_pull_archived_fallback_campaigns
  lib/ad_service/query/for_display.ex
  test/ad_service/query/for_display_test.exs
Labels: In progress

#380 Show real stats on home page
  .gitignore
  lib/code_fund/application.ex
  lib/code_fund/impressions/impressions.ex
  lib/code_fund/queries/impression.ex
  lib/code_fund/queries/user_impression.ex
  lib/code_fund/stats/user_impressions.ex
  lib/code_fund/user_impressions/user_impressions.ex
  lib/code_fund_web/templates/page/index.html.eex
  test/code_fund/queries/impression_test.ex
  test/code_fund/queries/user_impression_test.ex
  test/code_fund/stats/user_impressions_test.exs
Labels: Enhancement, In progress

#397 fix_fallback_campaign_display
  lib/ad_service/query/for_display.ex
  test/ad_service/query/for_display_test.exs
Labels: In progress

#398 rename test files
  lib/code_fund/queries/impression.ex
  lib/code_fund/queries/user_impression.ex
  lib/code_fund/user_impressions/user_impressions.ex
  test/code_fund/queries/impression_test.ex
  test/code_fund/queries/user_impression_test.ex
  test/code_fund/stats/user_impressions_test.exs
Labels: In progress

#403 Fix for mobile usage
  lib/code_fund_web/templates/layout/home.html.eex
  lib/code_fund_web/templates/user/index.html.eex
Labels: In progress

#404 handle_exits_on_when_no_ads_selected
  lib/ad_service/server.ex
Labels: In progress

#405 fix_timeout_on_user_impressions_query
  lib/code_fund/stats/user_impressions.ex
Labels: In progress

#406 fix_user_impressions_for_test
  lib/code_fund/stats/user_impressions.ex
  test/code_fund/stats/user_impressions_test.exs
Labels: In progress

#409 bean/gh-381_property_search
  lib/code_fund/properties/properties.ex
  lib/code_fund_web/templates/property/index.html.eex
Labels: In progress

#408 bean/ch-387_removing_property_tags
  lib/code_fund/schemas/property.ex
  test/code_fund/schemas/property_test.exs
Labels: In progress

#411 bean/gh-390_newrelic
  .gitignore
  lib/code_fund_web/router.ex
  mix.exs
  mix.lock
Labels: In progress

#391 bean/gh-372_deprecate_audiences
  assets/src/controllers/audience_form_controller.js
  lib/ad_service/query/for_audience_creation.ex
  lib/ad_service/query/shared.ex
  lib/code_fund/audiences/audiences.ex
  lib/code_fund/campaigns/campaigns.ex
  lib/code_fund/factory.ex
  lib/code_fund/properties/properties.ex
  lib/code_fund/schemas/audience.ex
  lib/code_fund/schemas/budgeted_campaign.ex
  lib/code_fund/schemas/campaign.ex
  lib/code_fund/schemas/property.ex
  lib/code_fund/schemas/user_impression.ex
  lib/code_fund/tasks/audience_tag_to_campaign_copy.ex
  lib/code_fund_web/controllers/api/audience_metrics_controller.ex
  lib/code_fund_web/controllers/audience_controller.ex
  lib/code_fund_web/controllers/campaign_controller.ex
  lib/code_fund_web/controllers/property_controller.ex
  lib/code_fund_web/router.ex
  lib/code_fund_web/templates/audience/form.html.eex
  lib/code_fund_web/templates/audience/index.html.eex
  lib/code_fund_web/templates/audience/show.html.eex
  lib/code_fund_web/templates/campaign/index.html.eex
  lib/code_fund_web/templates/campaign/show.html.eex
  lib/code_fund_web/templates/layout/admin.html.eex
  lib/code_fund_web/templates/property/index.html.eex
  lib/code_fund_web/views/api/audience_metrics_view.ex
  lib/code_fund_web/views/audience_view.ex
  priv/repo/migrations/20181011202739_regenerate_user_impressions_and_budgeted_campaigns_without_audiences.exs
  priv/repo/migrations/20181011202741_drop_audiences.exs
  priv/repo/migrations/20181011203443_redefine_materialized_view_indices_without_audiences.exs
  test/ad_service/impression/manager_test.exs
  test/ad_service/query/for_audience_creation_test.exs
  test/ad_service/query/for_display_test.exs
  test/ad_service/server_test.exs
  test/code_fund/audiences/audiences_test.exs
  test/code_fund/schemas/audience_test.exs
  test/code_fund_web/controllers/api/ad_serve_controller_test.exs
  test/code_fund_web/controllers/api/audience_metrics_controller_test.exs
  test/code_fund_web/controllers/audience_controller_test.exs
  test/code_fund_web/controllers/campaign_controller_test.exs
  test/code_fund_web/controllers/property_controller_test.exs
  test/tasks/audience_tag_to_campaign_copy_test.exs
Labels: In progress

#413 bean/gh-382_view_masquerade_links
  lib/code_fund_web/templates/property/show.html.eex
Labels: In progress

#410 bean/gh-374_maxmind_script
  lib/code_fund/tasks/maxmind.ex
Labels: In progress

#407 bean/ch-383_property_language
  lib/code_fund/schemas/property.ex
Labels: In progress

#414 Hard code user impression stats
  assets/package-lock.json
  lib/code_fund/application.ex
  lib/code_fund/stats/user_impressions.ex
  lib/code_fund_web/templates/page/index.html.eex
  test/code_fund/stats/user_impressions_test.exs
Labels: Bug, In progress
